apiVersion: v1
kind: Service
metadata:
  name: pymongo-master
  labels:
    app: pymongo
    role: master
    tier: backend
spec:
  ports:
    # the port that this service should serve on
  - port: 6379
    targetPort: 6379
  selector:
    app: pymongo
    role: master
    tier: backend
#-----------------------------------------------------
apiVersion: v1
kind: ReplicationController
metadata:
  name: pymongo-master
  # these labels can be applied automatically 
  # from the labels in the pod template if not set
  labels:
    app: pymongo
    role: master
    tier: backend
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 5
  # selector can be applied automatically 
  # from the labels in the pod template if not set
  # selector:
  #   app: guestbook
  #   role: master
  #   tier: backend
  template:
    metadata:
      labels:
        app: pymongo
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: naomifridman/pymongo:v2
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379